DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS food;
DROP TABLE IF EXISTS tracker;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE food (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  food_name TEXT UNIQUE NOT NULL,
  food_calorie TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE tracker (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tracking_date DATE NOT NULL DEFAULT (CURRENT_DATE),
  user_id INTEGER NOT NULL,
  food_id INTEGER NOT NULL,
  quantity TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user (id)
  FOREIGN KEY (food_id) REFERENCES food (id)
);